# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/heyo_nbdev',
                'doc_host': 'https://oxbits.github.io',
                'git_url': 'https://github.com/oxbits/heyo_nbdev',
                'lib_path': 'heyo_nbdev'},
  'syms': {'heyo_nbdev.core': {'heyo_nbdev.core.foo': ('core.html#foo', 'heyo_nbdev/core.py')}}}
