"""heyo_nbdev"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_heyo_nbdev.ipynb.

# %% auto #0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_heyo_nbdev.ipynb #a6929c81
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_heyo_nbdev.ipynb #d7947400
def foo(): pass
